
package edu.getty.tgn.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "TGNWebServicesSoap", targetNamespace = "http://vocabsservices.getty.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TGNWebServicesSoap {


    /**
     * Returns full set of TGN Nations (internal Getty use only)
     * 
     * @param nationText
     * @param nationId
     * @return
     *     returns edu.getty.tgn.service.ArrayOfListResults
     */
    @WebMethod(operationName = "TGNGetNations", action = "http://vocabsservices.getty.edu/TGNGetNations")
    @WebResult(name = "TGNGetNationsResult", targetNamespace = "http://vocabsservices.getty.edu/")
    @RequestWrapper(localName = "TGNGetNations", targetNamespace = "http://vocabsservices.getty.edu/", className = "edu.getty.tgn.service.TGNGetNations")
    @ResponseWrapper(localName = "TGNGetNationsResponse", targetNamespace = "http://vocabsservices.getty.edu/", className = "edu.getty.tgn.service.TGNGetNationsResponse")
    public ArrayOfListResults tgnGetNations(
        @WebParam(name = "nation_id", targetNamespace = "http://vocabsservices.getty.edu/")
        String nationId,
        @WebParam(name = "nation_text", targetNamespace = "http://vocabsservices.getty.edu/")
        String nationText);

    /**
     * Returns full set of ULAN Place Types (internal Getty use only)
     * 
     * @param ptypeText
     * @param ptypeId
     * @return
     *     returns edu.getty.tgn.service.ArrayOfListResults
     */
    @WebMethod(operationName = "TGNGetPtypes", action = "http://vocabsservices.getty.edu/TGNGetPtypes")
    @WebResult(name = "TGNGetPtypesResult", targetNamespace = "http://vocabsservices.getty.edu/")
    @RequestWrapper(localName = "TGNGetPtypes", targetNamespace = "http://vocabsservices.getty.edu/", className = "edu.getty.tgn.service.TGNGetPtypes")
    @ResponseWrapper(localName = "TGNGetPtypesResponse", targetNamespace = "http://vocabsservices.getty.edu/", className = "edu.getty.tgn.service.TGNGetPtypesResponse")
    public ArrayOfListResults tgnGetPtypes(
        @WebParam(name = "ptype_id", targetNamespace = "http://vocabsservices.getty.edu/")
        String ptypeId,
        @WebParam(name = "ptype_text", targetNamespace = "http://vocabsservices.getty.edu/")
        String ptypeText);

}
