
package edu.getty.tgn.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * TGN Web Services
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 *
 * @author mole
 * @version $Id: $Id
 */
@WebServiceClient(name = "TGNWebServices", targetNamespace = "http://vocabsservices.getty.edu/", wsdlLocation = "file:/home/mole/git/gen_gettytgn_client/src/main/resources/TGNService_minimal.wsdl")
public class TGNWebServices
    extends Service
{

    private final static URL TGNWEBSERVICES_WSDL_LOCATION;
    private final static WebServiceException TGNWEBSERVICES_EXCEPTION;
    private final static QName TGNWEBSERVICES_QNAME = new QName("http://vocabsservices.getty.edu/", "TGNWebServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/mole/git/gen_gettytgn_client/src/main/resources/TGNService_minimal.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TGNWEBSERVICES_WSDL_LOCATION = url;
        TGNWEBSERVICES_EXCEPTION = e;
    }

    /**
     * <p>Constructor for TGNWebServices.</p>
     */
    public TGNWebServices() {
        super(__getWsdlLocation(), TGNWEBSERVICES_QNAME);
    }

    /**
     * <p>Constructor for TGNWebServices.</p>
     *
     * @param features a {@link jakarta.xml.ws.WebServiceFeature} object.
     */
    public TGNWebServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), TGNWEBSERVICES_QNAME, features);
    }

    /**
     * <p>Constructor for TGNWebServices.</p>
     *
     * @param wsdlLocation a {@link java.net.URL} object.
     */
    public TGNWebServices(URL wsdlLocation) {
        super(wsdlLocation, TGNWEBSERVICES_QNAME);
    }

    /**
     * <p>Constructor for TGNWebServices.</p>
     *
     * @param wsdlLocation a {@link java.net.URL} object.
     * @param features a {@link jakarta.xml.ws.WebServiceFeature} object.
     */
    public TGNWebServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TGNWEBSERVICES_QNAME, features);
    }

    /**
     * <p>Constructor for TGNWebServices.</p>
     *
     * @param wsdlLocation a {@link java.net.URL} object.
     * @param serviceName a {@link javax.xml.namespace.QName} object.
     */
    public TGNWebServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * <p>Constructor for TGNWebServices.</p>
     *
     * @param wsdlLocation a {@link java.net.URL} object.
     * @param serviceName a {@link javax.xml.namespace.QName} object.
     * @param features a {@link jakarta.xml.ws.WebServiceFeature} object.
     */
    public TGNWebServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * <p>getTGNWebServicesSoap.</p>
     *
     * @return a {@link edu.getty.tgn.service.TGNWebServicesSoap} object.
     */
    @WebEndpoint(name = "TGNWebServicesSoap")
    public TGNWebServicesSoap getTGNWebServicesSoap() {
        return super.getPort(new QName("http://vocabsservices.getty.edu/", "TGNWebServicesSoap"), TGNWebServicesSoap.class);
    }

    /**
     * <p>getTGNWebServicesSoap.</p>
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return a {@link edu.getty.tgn.service.TGNWebServicesSoap} object.
     */
    @WebEndpoint(name = "TGNWebServicesSoap")
    public TGNWebServicesSoap getTGNWebServicesSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://vocabsservices.getty.edu/", "TGNWebServicesSoap"), TGNWebServicesSoap.class, features);
    }

    /**
     * <p>getTGNWebServicesSoap12.</p>
     *
     * @return a {@link edu.getty.tgn.service.TGNWebServicesSoap} object.
     */
    @WebEndpoint(name = "TGNWebServicesSoap12")
    public TGNWebServicesSoap getTGNWebServicesSoap12() {
        return super.getPort(new QName("http://vocabsservices.getty.edu/", "TGNWebServicesSoap12"), TGNWebServicesSoap.class);
    }

    /**
     * <p>getTGNWebServicesSoap12.</p>
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return a {@link edu.getty.tgn.service.TGNWebServicesSoap} object.
     */
    @WebEndpoint(name = "TGNWebServicesSoap12")
    public TGNWebServicesSoap getTGNWebServicesSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://vocabsservices.getty.edu/", "TGNWebServicesSoap12"), TGNWebServicesSoap.class, features);
    }

    /**
     * <p>getTGNWebServicesHttpGet.</p>
     *
     * @return a {@link edu.getty.tgn.service.TGNWebServicesHttpGet} object.
     */
    @WebEndpoint(name = "TGNWebServicesHttpGet")
    public TGNWebServicesHttpGet getTGNWebServicesHttpGet() {
        return super.getPort(new QName("http://vocabsservices.getty.edu/", "TGNWebServicesHttpGet"), TGNWebServicesHttpGet.class);
    }

    /**
     * <p>getTGNWebServicesHttpGet.</p>
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return a {@link edu.getty.tgn.service.TGNWebServicesHttpGet} object.
     */
    @WebEndpoint(name = "TGNWebServicesHttpGet")
    public TGNWebServicesHttpGet getTGNWebServicesHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://vocabsservices.getty.edu/", "TGNWebServicesHttpGet"), TGNWebServicesHttpGet.class, features);
    }

    /**
     * <p>getTGNWebServicesHttpPost.</p>
     *
     * @return a {@link edu.getty.tgn.service.TGNWebServicesHttpPost} object.
     */
    @WebEndpoint(name = "TGNWebServicesHttpPost")
    public TGNWebServicesHttpPost getTGNWebServicesHttpPost() {
        return super.getPort(new QName("http://vocabsservices.getty.edu/", "TGNWebServicesHttpPost"), TGNWebServicesHttpPost.class);
    }

    /**
     * <p>getTGNWebServicesHttpPost.</p>
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return a {@link edu.getty.tgn.service.TGNWebServicesHttpPost} object.
     */
    @WebEndpoint(name = "TGNWebServicesHttpPost")
    public TGNWebServicesHttpPost getTGNWebServicesHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://vocabsservices.getty.edu/", "TGNWebServicesHttpPost"), TGNWebServicesHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TGNWEBSERVICES_EXCEPTION!= null) {
            throw TGNWEBSERVICES_EXCEPTION;
        }
        return TGNWEBSERVICES_WSDL_LOCATION;
    }

}
